import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

function Doc() {
    return (
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <main className={styles.main}>
            
            <h2 className={styles.title}>
                wizoscopo API &#10024;
            </h2>
            
        
    
         
    
            <div className={styles.grid}>
              <div className={styles.carddoc}>
                   <p className={styles.description}>
              API endpoint : {' '}
              <code className={styles.code}>/api/horoscope</code>
            </p>
            
                <br /> 
                <h2>Get message: </h2>
                <p> add to endpoint path parameter:</p>
                <code className={styles.code}>?sign=<italic className={styles.italic}>youritaliansign</italic></code>
                <br />  <br />  
                <p>All messages are provided in 🇮🇹 language. </p>
                <p> Weekly horoscope by Rob Breszny, from Thursday to Wednesday.</p> <br /> 
                <h2>Example for Virgo sign: </h2>
                <a className={styles.italic_link} href="http://localhost:3000/api/horoscope?sign=vergine">http://localhost/api/horoscope?sign=vergine</a>
              </div>
              </div>
           
              <br />  <br />
             
    
              <a
              href="https://github.com/wiztoth"
              target="_blank"
              rel="noopener noreferrer"
            >
              
              <span className={styles.logo}>
                <Image src="/octocat.svg" alt="Github Logo" width={100} height={45} />
              </span>
            </a>
            
            
          </main>
    
      
        </div>
      )



  }
  
  export default Doc